FROM alpine:3.23@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11

LABEL maintainer="openCloud Team team@opencloud.eu" \
  org.opencontainers.image.title="openCloud CI clamav Image" \
  org.opencontainers.image.vendor="openCloud GmbH" \
  org.opencontainers.image.authors="openCloud GmbH" \
  org.opencontainers.image.description="Custom clamav image for CI" \
  org.opencontainers.image.documentation="https://github.com/opencloud-eu/container-ci" \
  org.opencontainers.image.url="https://github.com/opencloud-eu/container-ci" \
  org.opencontainers.image.source="https://github.com/opencloud-eu/container-ci"

RUN apk add --update --no-cache bash clamav clamav-libunrar

RUN mkdir -p /run/clamav && \
    chown clamav:clamav /run/clamav && \
    chmod 750 /run/clamav

RUN echo "Foreground true" >> /etc/clamav/clamd.conf && \
    echo "TCPSocket 3310" >> /etc/clamav/clamd.conf && \
    echo "TCPAddr 0.0.0.0" >> /etc/clamav/clamd.conf

EXPOSE 3310

COPY run.sh /run.sh
RUN chmod +x /run.sh

CMD ["/run.sh"]
