FROM quay.io/minio/mc:RELEASE.2025-08-13T08-35-41Z AS upstream

FROM alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

LABEL maintainer="openCloud Team team@opencloud.eu" \
  org.opencontainers.image.title="openCloud CI minio-mc Image" \
  org.opencontainers.image.vendor="openCloud GmbH" \
  org.opencontainers.image.authors="openCloud GmbH" \
  org.opencontainers.image.description="MinIO client (mc) image for CI cache handling" \
  org.opencontainers.image.documentation="https://github.com/opencloud-eu/container-ci" \
  org.opencontainers.image.url="https://github.com/opencloud-eu/container-ci" \
  org.opencontainers.image.source="https://github.com/opencloud-eu/container-ci"

RUN apk add --update --no-cache bash ca-certificates curl zip

COPY --from=upstream /usr/bin/mc /usr/bin/mc

RUN mc --version

CMD ["mc"]
