FROM nvidia/cuda:13.2.1-base-ubuntu24.04

LABEL maintainer="openCloud Team team@opencloud.eu" \
  org.opencontainers.image.title="openCloud CI android emulator Image" \
  org.opencontainers.image.vendor="openCloud GmbH" \
  org.opencontainers.image.authors="openCloud GmbH" \
  org.opencontainers.image.description="Custom Android emulator image for CI" \
  org.opencontainers.image.documentation="https://github.com/opencloud-eu/container-ci" \
  org.opencontainers.image.url="https://github.com/opencloud-eu/container-ci" \
  org.opencontainers.image.source="https://github.com/opencloud-eu/container-ci" \
  org.opencontainers.image.version="1.0.0" \
  org.opencontainers.image.licenses="MIT" \
  org.opencontainers.image.base.name="github.com/HQarroum/docker-android" \
  android.api.level="36" \
  android.version="16"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update -y && \
    apt install -y --no-install-recommends \
    bash \
    unzip \
    wget \
    libvirt-daemon \
    dbus \
    openjdk-21-jre-headless \
    virt-manager \
    libvulkan1 \
    xvfb \
    libgl1-mesa-dri \
    socat \
    htop \
    iproute2 && \
    rm -rf /var/lib/apt/lists/*

ARG API_LEVEL=36
ARG IMG_TYPE=default
ARG ARCHITECTURE=x86_64
ARG DEVICE_ID=pixel
ARG CMD_LINE_VERSION=11076708_latest
ARG GPU_ACCELERATED=true
ARG INSTALL_ANDROID_SDK=1

ENV ANDROID_SDK_ROOT=/opt/android \
    ANDROID_PLATFORM_VERSION="platforms;android-$API_LEVEL" \
    PACKAGE_PATH="system-images;android-${API_LEVEL};${IMG_TYPE};${ARCHITECTURE}" \
    API_LEVEL=$API_LEVEL \
    DEVICE_ID=$DEVICE_ID \
    ARCHITECTURE=$ARCHITECTURE \
    ABI=${IMG_TYPE}/${ARCHITECTURE} \
    GPU_ACCELERATED=$GPU_ACCELERATED \
    QTWEBENGINE_DISABLE_SANDBOX=1 \
    ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL=10 \
    ANDROID_AVD_HOME=/data

# Exporting environment variables for keeping in the path
# Android SDK binaries and shared libraries.
ENV PATH="${PATH}:${ANDROID_SDK_ROOT}/platform-tools"
ENV PATH="${PATH}:${ANDROID_SDK_ROOT}/emulator"
ENV PATH="${PATH}:${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin"
ENV LD_LIBRARY_PATH="$ANDROID_SDK_ROOT/emulator/lib64:$ANDROID_SDK_ROOT/emulator/lib64/qt/lib"

# Set the working directory to /opt
WORKDIR /opt

# Exposing the Android emulator console port
# and the ADB port.
EXPOSE 5554 5555

# Initializing the required directories.
RUN mkdir /root/.android/ && \
  touch /root/.android/repositories.cfg && \
  mkdir /data

# The following layers will download the Android command-line tools
# to install the Android SDK, emulator and system images.
# It will then install the Android SDK and emulator.
COPY scripts/install-sdk.sh /opt/
RUN chmod +x /opt/install-sdk.sh
RUN /opt/install-sdk.sh

# Copy the container scripts in the image.
COPY scripts/start-emulator.sh /opt/
COPY scripts/emulator-monitoring.sh /opt/
RUN chmod +x /opt/*.sh
# Set the entrypoint
ENTRYPOINT ["/opt/start-emulator.sh"]
