---
variables:
  - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:latest'
  - &publish_repos "opencloudeu/notation,quay.io/opencloudeu/notation,registry.heinlein.group/opencloud/notation"
  - &publish_platforms 'linux/arm64,linux/amd64'
  - publish_logins: &publish_logins
    - registry: https://index.docker.io/v1/
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    - registry: https://quay.io
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
    - registry: https://registry.heinlein.group
      username:
        from_secret: harbor_opencloud_user
      password:
        from_secret: harbor_opencloud_password

when:
  - branch: ${CI_REPO_DEFAULT_BRANCH}
    path:
      - notation/**
    event:
      - push
  - branch: ${CI_REPO_DEFAULT_BRANCH}
    event:
      - manual
      - cron
  - event: pull_request
    path:
      - notation/**

steps:
  - image: *buildx_plugin
    name: dryrun
    settings:
      context: ./notation
      dockerfile: notation/Dockerfile
      dry_run: true
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      platforms: *publish_platforms
      pull_image: false
      repo: *publish_repos
      tag: pr-${CI_COMMIT_PULL_REQUEST}
    when:
      - event: pull_request

  - image: *buildx_plugin
    name: build-and-push
    settings:
      auto_tag: true
      context: ./notation
      default_tag: commit-${CI_COMMIT_SHA}
      dockerfile: notation/Dockerfile
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      logins: *publish_logins
      platforms: *publish_platforms
      pull_image: false
      repo: *publish_repos
      tag: latest
    when:
      - event:
          - cron
          - push
          - manual
      - event: tag
