---
variables:
  - &sign_image registry.heinlein.group/opencloud/notation:latest
  - &notation_conf "ewogICAgImRlZmF1bHQiOiAicmVnaXN0cnkiLAogICAgImtleXMiOiBbCiAgICAgICAgewogICAgICAgICAgICAibmFtZSI6ICJvYy1jaSIsCiAgICAgICAgICAgICJrZXlQYXRoIjogIi9yb290Ly5jb25maWcvbm90YXRpb24vbG9jYWxrZXlzL29jLWNpLmtleSIsCiAgICAgICAgICAgICJjZXJ0UGF0aCI6ICIvcm9vdC8uY29uZmlnL25vdGF0aW9uL2xvY2Fsa2V5cy9vYy1jaS5jcnQiCiAgICAgICAgfQogICAgXQp9Cg=="
  - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:latest'
  - &publish_repos "opencloudeu/notation,quay.io/opencloudeu/notation,registry.heinlein.group/opencloud/notation"
  - &publish_platforms 'linux/arm64,linux/amd64'
  - publish_logins: &publish_logins
    - registry: https://index.docker.io/v1/
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    - registry: https://quay.io
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
    - registry: https://registry.heinlein.group
      username:
        from_secret: harbor_opencloud_user
      password:
        from_secret: harbor_opencloud_password

when:
  - branch: ${CI_REPO_DEFAULT_BRANCH}
    path:
      - notation/**
    event:
      - push
  - branch: ${CI_REPO_DEFAULT_BRANCH}
    event:
      - manual
      - cron
  - event: pull_request
    path:
      - notation/**
  - event:
      - push

steps:
  - name: dryrun
    image: *buildx_plugin
    settings:
      context: ./notation
      dockerfile: notation/Dockerfile
      dry_run: true
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      platforms: *publish_platforms
      pull_image: false
      repo: *publish_repos
      tag: pr-${CI_COMMIT_PULL_REQUEST}
    when:
      - event: pull_request

  - name: build-and-push
    image: *buildx_plugin
    settings:
      auto_tag: true
      context: ./notation
      default_tag: commit-${CI_COMMIT_SHA}
      dockerfile: notation/Dockerfile
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      logins: *publish_logins
      platforms: *publish_platforms
      pull_image: false
      repo: *publish_repos
      tag: latest
    when:
      - event:
          - cron
          - push
          - manual
      - event: tag

  - name: sign
    image: *sign_image
    environment:
      NOTATION_KEY:
        from_secret: notation_key
      NOTATION_CERT:
        from_secret: notation_cert
      NOTATION_CONF: *notation_conf
    commands:
      - echo "$$NOTATION_CONF" | base64 -d > /root/.config/notation/signingkeys.json
      - echo "$$NOTATION_KEY" | base64 -d > /root/.config/notation/localkeys/oc-ci.key
      - echo "$$NOTATION_CERT" | base64 -d > /root/.config/notation/localkeys/oc-ci.crt
      - notation key list
      - notation cert list
    #default_tag: commit-${CI_COMMIT_SHA}
    #tag: latest
    when:
      - event:
          - cron
          - push
          - manual
      - event: tag
