---
variables:
  - &sign_image registry.heinlein.group/opencloud/notation-wp-plugin:latest
  - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:latest'
  - &publish_repos "opencloudeu/notation-wp-plugin,quay.io/opencloudeu/notation-wp-plugin,registry.heinlein.group/opencloud/notation-wp-plugin"
  - &publish_platforms 'linux/arm64,linux/amd64'
  - publish_logins: &publish_logins
    - registry: https://index.docker.io/v1/
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    - registry: https://quay.io
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
    - registry: https://registry.heinlein.group
      username:
        from_secret: harbor_opencloud_user
      password:
        from_secret: harbor_opencloud_password
  - readme_env: &readme_env
      PUSHRM_FILE: notation-wp-plugin/docs.md
      PUSHRM_SHORT: Woodpecker-CI plugin for Notation

when:
  - branch: ${CI_REPO_DEFAULT_BRANCH}
    path: notation-wp-plugin/**
    event:
      - push
  - branch: ${CI_REPO_DEFAULT_BRANCH}
    event:
      - manual
      - cron
  - event: pull_request
    path: 'notation-wp-plugin/**'

steps:
  - name: dryrun
    image: *buildx_plugin
    settings:
      context: ./notation-wp-plugin
      dockerfile: notation-wp-plugin/Dockerfile
      dry_run: true
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      platforms: *publish_platforms
      pull_image: true
      repo: *publish_repos
      tag: pr-${CI_COMMIT_PULL_REQUEST}
    when:
      - event: pull_request

  - name: build-and-push
    image: *buildx_plugin
    settings:
      auto_tag: true
      context: ./notation-wp-plugin
      default_tag: commit-${CI_COMMIT_SHA}
      dockerfile: notation-wp-plugin/Dockerfile
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      logins: *publish_logins
      platforms: *publish_platforms
      repo: *publish_repos
      tag: latest
    when:
      - branch: ${CI_REPO_DEFAULT_BRANCH}
        event:
          - cron
          - push
          - manual
        path: notation-wp-plugin/**
      - event: tag

  - name: sign
    image: *sign_image
    pull: true
    settings:
      key:
        from_secret: notation_key
      crt:
        from_secret: notation_cert
      logins: *publish_logins
      target: registry.heinlein.group/opencloud/notation-wp-plugin:commit-${CI_COMMIT_SHA}
      additional:
        - docker.io/opencloudeu/notation-wp-plugin
        - quay.io/opencloudeu/notation-wp-plugin
    when:
      - branch: ${CI_REPO_DEFAULT_BRANCH}
        event:
          - cron
          - push
          - manual
      - event: tag

  - name: readme-docker
    image: chko/docker-pushrm:1
    environment:
      <<: *readme_env
      PUSHRM_TARGET: opencloudeu/notation-wp-plugin
      DOCKER_PASS:
        from_secret: docker_password
      DOCKER_USER:
        from_secret: docker_username
    when: &readme_when
      - branch: add_readme
        event:
          - push
        path:
          - notation-wp-plugin/docs.md

  - name: readme-quay
    image: chko/docker-pushrm:1
    environment:
      <<: *readme_env
      PUSHRM_TARGET: quay.io/opencloudeu/notation-wp-plugin
      PUSHRM_PROVIDER: quay
      APIKEY__QUAY_IO:
        from_secret: quay_apikey
    when: *readme_when

  - name: readme-harbor
    image: chko/docker-pushrm:1
    environment:
      <<: *readme_env
      PUSHRM_TARGET: registry.heinlein.group/opencloud/notation-wp-plugin
      PUSHRM_PROVIDER: harbor2
      DOCKER_PASS:
        from_secret: harbor_opencloud_password
      DOCKER_USER:
        from_secret: harbor_opencloud_user
    when: *readme_when
