---
variables:
  - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:latest'
  - &publish_repos 'opencloudeu/wait-for-ci,quay.io/opencloudeu/wait-for-ci'
  - &publish_platforms 'linux/arm64,linux/amd64'
  - publish_logins: &publish_logins
    - registry: https://index.docker.io/v1/
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    - registry: https://quay.io
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
    - registry: https://registry.heinlein.group
      username:
        from_secret: harbor_opencloud_user
      password:
        from_secret: harbor_opencloud_password
when:
  - event: [push, manual, cron]
    branch: ${CI_REPO_DEFAULT_BRANCH}
    path: 'wait-for/**'
  - event: pull_request
  - event: tag

steps:
  - name: dryrun
    image: *buildx_plugin
    settings:
      context: ./wait-for
      dockerfile: wait-for/Dockerfile.multiarch
      dry_run: true
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      platforms: *publish_platforms
      pull_image: true
      repo: *publish_repos
      tag: pr-${CI_COMMIT_PULL_REQUEST}
    when:
      - event: pull_request

  - name: build-and-push
    image: *buildx_plugin
    settings:
      auto_tag: true
      context: ./wait-for
      default_tag: commit-${CI_COMMIT_SHA}
      dockerfile: wait-for/Dockerfile.multiarch
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      logins: *publish_logins
      platforms: *publish_platforms
      repo: *publish_repos
      tags:
        - latest
    when:
      - branch: ${CI_REPO_DEFAULT_BRANCH}
        event:
          - push
      - event: tag
