---
variables:
  - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:latest'
  - &publish_repos 'opencloudeu/wopi-validator,quay.io/opencloudeu/wopi-validator'
  - &publish_platforms 'linux/amd64'
  - publish_logins: &publish_logins
      - registry: https://index.docker.io/v1/
        username:
          from_secret: docker_username
        password:
          from_secret: docker_password
      - registry: https://quay.io
        username:
          from_secret: quay_username
        password:
          from_secret: quay_password
      - registry: https://registry.heinlein.group
        username:
          from_secret: harbor_opencloud_user
        password:
          from_secret: harbor_opencloud_password
when:
  - event: [push, manual, cron]
    branch: ${CI_REPO_DEFAULT_BRANCH}
    path:
      - 'wopi-validator/**'
      - '.woodpecker/wopi-validator.yml'
  - event: pull_request
  - event: tag

steps:
  - name: dryrun
    image: *buildx_plugin
    settings:
      context: ./wopi-validator
      dockerfile: wopi-validator/Dockerfile
      dry_run: true
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      platforms: *publish_platforms
      pull_image: true
      repo: *publish_repos
      tag: pr-${CI_COMMIT_PULL_REQUEST}
    when:
      - event: pull_request

  - name: build-and-push
    image: *buildx_plugin
    settings:
      auto_tag: true
      context: ./wopi-validator
      default_tag: commit-${CI_COMMIT_SHA}
      dockerfile: wopi-validator/Dockerfile
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      logins: *publish_logins
      platforms: *publish_platforms
      repo: *publish_repos
      tags:
        - latest
    when:
      - branch: ${CI_REPO_DEFAULT_BRANCH}
        event:
          - push
      - event: tag
